name: Deploy to Cloud Run

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
        with:
          version: '333.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - run: |
          cd ./back-end
          gcloud auth configure-docker
          gcloud components install beta
      - run: |
          cd ./back-end
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name .
      - run: |
          cd ./back-end
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name
      - run: |
          cd ./back-end
          gcloud beta run deploy your-app-name --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/your-app-name --platform managed --region your-region
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}